model_params:
    model_name: Baseline
    structured_params:
        structured_input_dim: 21
    deep_params:
        out_dim: 60
        in_channels: 1
        dimensions: 2
        architecture: 'ResidualClassifier'
        hidden_channels: [32, 64, 128, 256]
        kernel_sizes: [5, 3, 3, 3]
        strides: [2, 2, 2, 2]
        padding: [2, 1, 1, 1]
        bottleneck: True
    wide_deep_params:
        orthogonalize: True
        output_dim: 1
    
model_hyperparams:
    loss_type: 'cox_ph'

exp_params:
    dataset: 'adni'
    data_path: 'data/coxph/'
    base_folder: 'adni2d'
    data_type: 'coxph'
    simulate: False
    n_dim: 1
    batch_size: 256
    optimizer: 'AdamW'
    learning_rate: 0.0000335
    scheduler_gamma: 0.99456
    weight_decay: 13.13
    max_epochs: 50
    transforms: True

baseline_params:
    baseline: 'stargan'
    c_dim: 2
    img_size: 28
    tolerance: 0.5
    discriminator_params:
        learning_rate: 0.001
        beta1: 0.5
        beta2: 0.999
        dimensions: 2
        repeat_num: 3
        conv_dim: 16
        n_dim: 1
    generator_params:
        learning_rate: 0.001
        beta1: 0.5
        beta2: 0.999
        dimensions: 2
        c_dim: 2
        repeat_num: 6
        conv_dim: 16
        n_dim: 1
    trainer_params:
        n_steps: 60000
        dataset: 'idk'
        n_critic: 5
        log_step: 1000
        sample_step: 1000
        #lambda_cls: 500.0
        lambda_cls: 500.0
        #lambda_rec: 2.1
        lambda_rec: 20.0    
        #lambda_gp: 1.1
        lambda_gp: 10.0
        lambda_map: 49.0
        lambda_tv: 10.0
        #lambda_tv: 16.0
        st: False
    logging_params:
        storage_path: 'wo_map'
        run_name: 'wo_map'

trainer_params:
    #gpu: 1
    #max_epochs: 1
    max_epochs: 150
  
logging_params:
    manual_seed: 1234
    save_dir: 'logging'