model_params:
    model_name: Linear
    structured_params:
        #structured_input_dim: 1
        structured_input_dim: 21  
    wide_deep_params:
        output_dim: 1
    
model_hyperparams:
    loss_type: 'cox_ph'

exp_params:
    dataset: 'adni'
    data_path: 'data/coxph/'
    base_folder: 'adni2d'
    data_type: 'coxph'
    simulate: False
    n_dim: 1
    batch_size: 610
    optimizer: 'SGD'
    learning_rate: 0.0025
    #scheduler_gamma: 0.95
    weight_decay: 0
    max_epochs: 50
    transforms: False

baseline_params:
    baseline: 'stargan'
    c_dim: 2
    img_size: 28
    tolerance: 0.5
    discriminator_params:
        learning_rate: 0.001
        beta1: 0.5
        beta2: 0.999
        dimensions: 2
        repeat_num: 3
        conv_dim: 16
        n_dim: 1
    generator_params:
        learning_rate: 0.0001
        beta1: 0.5
        beta2: 0.999
        dimensions: 2
        c_dim: 2
        repeat_num: 6
        conv_dim: 16
        n_dim: 1
    trainer_params:
        n_steps: 60000
        dataset: 'idk'
        n_critic: 5
        log_step: 1000
        sample_step: 1000
        #lambda_cls: 500.0
        lambda_cls: 500.0
        #lambda_rec: 2.1
        lambda_rec: 20.0    
        #lambda_gp: 1.1
        lambda_gp: 10.0
        lambda_map: 49.0
        lambda_tv: 10.0
        #lambda_tv: 16.0
        st: False
    logging_params:
        storage_path: 'wo_map'
        run_name: 'wo_map'

trainer_params:
    #gpu: 1
    #max_epochs: 1
    max_epochs: 2000
  
logging_params:
    manual_seed: 1234
    save_dir: 'logging'